<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\user\Entity\User;
use Drupal\profile\Entity\Profile;
use Drupal\Core\Url;
use Drupal\group\Entity\GroupContent;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_profile_insert().
 */
function efn_users_profile_insert(EntityInterface $profile) {
	// Add appropriate roles when user completes profile. Names should match.
	if (in_array($profile->bundle(), ['volunteer', 'researcher'])) {
		$user = $profile->getOwner();
		$user->addRole($profile->bundle());
		$user->save();
	}
}

/**
 * Implements hook_form_BASE_FORM_ID_alter.
 */
function efn_users_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	// Redirect to a better place after registration
	$form['actions']['submit']['#submit'][] = 'efn_users_user_register_form_submit';
}

/**
 * Custom submit function to redirect to user login page after register
 */
function efn_users_user_register_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
	$redirect_url = Url::fromRoute('user.login');
	$form_state->setRedirectUrl($redirect_url);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter.
 */
function efn_users_form_profile_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	// is it a profile?
	if (in_array('profile-form',$form['#attributes']['class'])){
		$cuser = \Drupal::currentUser();
		// user of currently viewed profile form
		$puser = \Drupal::routeMatch()->getParameter('user')->id();

		if (($cuser->id()!=$puser) & !(in_array('administrator', $cuser->getRoles($exclude_locked_roles = false) ))) {
			// deny access to non -owners of form
			$form["#access"]=FALSE;
		}
		$form['actions']['set_default']['#access']=FALSE;
	}

}

/**
 * Implements hook_form_alter.
 */
function efn_users_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	if ($form_id == 'group_content_project-group_membership_group-join_form') {
	    $form['actions']['submit']['#submit'][] = 'send_to_project';
	  }
}

/**
 * Contact form submit handler
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function send_to_project(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
	$entity = $form_state->getFormObject()->getEntity();
	$group= $entity-> getGroup();

	// Group will have new content so invalidate group tags. But this won't work no matter how we call the Cache class. why? seems to work without clearing caches anyhow ??
	// $tags = $group->getCacheTagsToInvalidate();
	// \Drupal\Core\Cache::invalidateTags($tags);

	// Now redirect to the url of the group.
	$route_params = ['group' => $group->id()];
	$form_state->setRedirect('entity.group.canonical', $route_params);

	drupal_set_message(t('Thanks for joining the Project. The project owner will be in touch with you soon!'));
}
