<?php

/**
 * Implements hook_entity_type_alter().
 */
function auto_entitylabel_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if (($entity_type->getFormClass('default') || $entity_type->getFormClass('edit')) && $entity_type->hasLinkTemplate('edit-form')) {
      $entity_type->setLinkTemplate('auto-label', "/auto-label/$entity_type_id/{{$entity_type_id}}");
    }
  }
}