# Schema for the configuration files of the auto_nodetitle module.

auto_nodetitle.node.*:
  type: mapping
  label: 'The auto node title settings'
  mapping:
    status:
      type: integer
      label: 'Preview before submitting'
    php:
      type: integer
      label: 'The auto node php settings'
    pattern:
      type: string
      label: 'The auto node pattern settings'

action.configuration.auto_nodetitle_update_action:
  type: action_configuration_default
  label: 'Update automatic nodetitles'