module:
  address: 0
  admin_toolbar: 0
  ajax_comments: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_exclude_pages: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  comment: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  default_content: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  efn: 0
  efn_default_content: 0
  efn_users: 0
  email_registration: 0
  entity: 0
  field: 0
  field_group: 0
  field_states_ui: 0
  field_ui: 0
  file: 0
  filter: 0
  geocoder: 0
  geofield: 0
  geophp: 0
  gnode: 0
  group: 0
  hal: 0
  help: 0
  image: 0
  kint: 0
  leaflet: 0
  leaflet_more_maps: 0
  link: 0
  markup: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  profile: 0
  quickedit: 0
  rest: 0
  serialization: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_data_export: 0
  views_send: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  pathauto: 1
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  minimus: 0
  bartik: 0
profile: minimal
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
