definitions:
  contact__site_page:
    weight: -46
    menu_name: footer
    parent: ''
    expanded: false
    enabled: false
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
