cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/png
  path: 'public://bean_0.png'
  url: 'http://efn.localhost/sites/default/files/bean.png'
  use_default: false
schemas:
  bootstrap: 8000
  minimus: 8000
fluid_container: 1
table_responsive: '-1'
table: ''
logo:
  path: themes/minimus/images/efn_logo_long_bold.png
  url: ''
  use_default: false
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
breadcrumb: '0'
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
