smtp_on: true
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: apikey
smtp_password: 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
smtp_from: efn@radicante.net
smtp_fromname: 'Experimental Farm Network'
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
smtp_client_hostname: ''
smtp_client_helo: ''
