smtp_on: true
smtp_host: fleetwood.websitewelcome.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: efn@radicante.media
smtp_password: 2P114ICg21qf4osO
smtp_from: efn@radicante.media
smtp_fromname: efn
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
