smtp_on: true
smtp_host: mail.radicante.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: efn@radicante.net
smtp_password: lCn9hA9AgcZDW9
smtp_from: efn@radicante.net
smtp_fromname: efn
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
