# Schema for the views plugins of the Group module.

views.argument_default.group_id_from_url:
  type: sequence
  label: 'Group ID from current route'
  sequence:
    type: string
    label: 'Group ID'
